### ISSUE TITLE
如何输出大尺寸的图片呢?我看最大是384，大于384怎么办? /How to output large-sized images? I think the maximum is 384. What if it is greater than 384?

### ISSUE THREAD

**Issue by gg22mm** [JJJYmmm/Pix2SeqV2-Pytorch#2]
如何输出大尺寸的图片呢?我看最大是384，大于384怎么办? /  How to output large-sized images? I think the maximum is 384. What if it is greater than 384?

**Comment by JJJYmmm** [comment]
change `img_size` in config.py 
https://github.com/JJJYmmm/Pix2SeqV2-Pytorch/blob/b8ffe137a2260ded41a6ad564797c8a4cb361a97/config.py#L14C12-L14C12
