### ISSUE TITLE
 发现个问题：  --box selected_area   为什么还手动填进去，不是自动获取， 我怎么知道 box在哪个地方 ？/ Found an issue: -- box selected_ Why is area manually filled in instead of automatically obtained? How do I know where the box is?

### ISSUE THREAD

**Issue by gg22mm** [JJJYmmm/Pix2SeqV2-Pytorch#3]
# 例子/example
cd infer
python infer_single_image_segmentation.py --image your_image_path --box selected_area(format:xywh)

发现个问题：  --box selected_area   为什么还手动填进去，不是自动获取， 我怎么知道 box在哪个地方 ？ / Found an issue: -- box selected_ Why is area manually filled in instead of automatically obtained? How do I know where the box is?

**Comment by JJJYmmm** [comment]
For segmentation and keypoint tasks, Pix2SeqV2 uses a top-down paradigm. Therefore, you need to provide the model with the location of the cropped image(containing the object or persons). You can run the model with detection task(see https://github.com/JJJYmmm/Pix2SeqV2-Pytorch/blob/master/infer/infer_single_image_multi_task.py) or use other detectors  to get the boxes of objects.
