### ISSUE TITLE
Baidu links don't work. 

### ISSUE THREAD

**Issue by rnaveensrinivas** [JJJYmmm/Pix2SeqV2-Pytorch#4]
Hi, 
the codebase is great. :)

I tried training the code for one epoch on Kaggle P100. 
But the training time for 1epoch was est. to be 14hours. 
Is it possible to that you can share the multi-task weights?

I have trained individual tasks; they work perfectly fine. it's just this multi-task that is simply not possible to train.

**Comment by JJJYmmm** [comment]
Thank you for your feedback! 

You can find the trained multi-task weights at [here](https://pan.baidu.com/s/1NKrsdx-Qsh0qJ-qhJY694A?pwd=1212) (I just check the link, it's called **coco_multi_task.pth** or **coco_multi_task_2.pth**). 

Indeed, training multi-task models can be challenging, as mentioned in the readme. The model I eventually trained performed poorly on the keypoint task, but at least I can see some progress on the other tasks. Maybe with great resources, miracles can happen.

Actually, this is a toy project for me to explore the multi-modal domain, and I apologize for not having the additional time and resources to provide well-trained weights and clean code. : )

**Comment by JJJYmmm** [comment]
I uploaded **coco_multi_task.pth** to [google drive](https://drive.google.com/file/d/12VUEfhBopblnjSqPQAFrij_5uXAGMO8T/view?usp=sharing).
